### PR TITLE
Bump major version to 3.0.0.

### PR DESCRIPTION
**Pull request by ordavidil**
Bumped the version due to #21

### CODE REVIEW

**Comment by ordavidil** [comment]
```
$ elm-package bump

Based on your new API, this should be a MAJOR change (2.1.0 => 3.0.0)
Bail out of this command and run 'elm-package diff' for a full explanation.

Should I perform the update (2.1.0 => 3.0.0) in elm-package.json? [Y/n]
```

```
$ elm-package diff

Comparing Gizra/elm-restful 2.1.0 to local changes...
This is a MAJOR change.

------ Changes to module Restful.Login - MAJOR ------

    Added:
        tryOneTimeLogin : Restful.Endpoint.BackendUrl -> List (String, String) -> Restful.Login.Msg user

    Changed:
      - type LoginMethod = ByAccessToken | ByPassword
      + type LoginMethod
            = ByAccessToken | ByOneTimeLogin | ByPassword

      - type alias Config anonymousData user authenticatedData msg =
            { loginPath : String,
              logoutPath : Maybe.Maybe String,
              userPath : String,
              decodeAccessToken : Json.Decode.Decoder Restful.Endpoint.AccessToken,
              decodeUser : Json.Decode.Decoder user,
              encodeUser : Maybe.Maybe (user -> Json.Encode.Value),
              initialAuthenticatedData : anonymousData -> user -> authenticatedData,
              initialAnonymousData : anonymousData,
              cacheCredentials : Restful.Endpoint.BackendUrl -> String -> Platform.Cmd.Cmd msg,
              tag : Restful.Login.Msg user -> msg
            }
      + type alias Config anonymousData user authenticatedData msg =
            { loginPath : String,
              oneTimeLoginPath : String,
              logoutPath : Maybe.Maybe String,
              userPath : String,
              decodeAccessToken : Json.Decode.Decoder Restful.Endpoint.AccessToken,
              decodeUser : Json.Decode.Decoder user,
              encodeUser : Maybe.Maybe (user -> Json.Encode.Value),
              initialAuthenticatedData : anonymousData -> user -> authenticatedData,
              initialAnonymousData : anonymousData,
              cacheCredentials : Restful.Endpoint.BackendUrl -> String -> Platform.Cmd.Cmd msg,
              tag : Restful.Login.Msg user -> msg
            }
```

**Comment by ordavidil** [comment]
//cc @amitaibu

**Comment by ordavidil** [comment]
```
$ elm-package publish

Verifying Gizra/elm-restful 3.0.0 ...
Version number 3.0.0 verified (MAJOR change, 2.1.0 => 3.0.0)
Success!
```

**Comment by ordavidil** [comment]
For some reason, I still don't see it published:
https://package.elm-lang.org/packages/Gizra/elm-restful
Gizra_elm-restful

**Comment by amitaibu** [comment]
Yeah, 0.18 are in a different site. I see it here -- https://old.elm.dmy.fr/packages/Gizra/elm-restful/latest

image

**Pull request merged**
